"""
Core domain package for Insurance Adjudication System
Contains exceptions, interfaces, types, utilities, and domain services
"""

from .exceptions import *
from .interfaces import *
from .types import *
from .utils import (
    parse_json_from_llm_response,
    safe_json_serialize,
    generate_claim_number,
    generate_workflow_id,
    generate_batch_id,
    validate_claim_amount,
    format_currency,
    is_round_number,
    ensure_timezone_aware,
    days_between,
    is_future_date,
    chunk_list,
    deduplicate_by_key,
    safe_get_nested,
    truncate_string,
    sanitize_for_logging,
    RetryConfig,
    validate_uuid,
    validate_email,
    validate_policy_number,
)
from .error_handler import (
    ErrorResponse,
    exception_to_response,
    get_http_status,
    handle_exception,
    create_error_handlers,
    error_boundary,
    raise_not_found,
    raise_validation_error,
    raise_circuit_open,
    raise_rate_limit,
    Result,
)

__all__ = [
    # Exceptions
    "AdjudicatorError",
    "DomainError",
    "ValidationError",
    "NotFoundError",
    "PolicyNotFoundError",
    "ClaimNotFoundError",
    "PolicyHolderNotFoundError",
    "AuthenticationError",
    "AuthorizationError",
    "RateLimitError",
    "ExternalServiceError",
    "LLMServiceError",
    "DatabaseError",
    "CircuitOpenError",
    "FraudDetectionError",
    "CoverageError",
    "InsufficientCoverageError",
    "PolicyExpiredError",
    "PolicyInactiveError",
    "ConfigurationError",
    "AgentError",
    "AgentExecutionError",
    "AgentTimeoutError",
    "WorkflowError",
    # Interfaces
    "IClaimRepository",
    "IPolicyRepository",
    "IAuditLogger",
    "IMetricsCollector",
    "ILLMClient",
    "IAgent",
    "IOrchestrator",
    "IEncryptor",
    "IRateLimiter",
    "ICircuitBreaker",
    # Types
    "ClaimData",
    "PolicyData",
    "DecisionData",
    "FraudAnalysisResult",
    "CoverageAnalysisResult",
    "DocumentExtractionResult",
    "AgentExecutionResult",
    # Utilities
    "parse_json_from_llm_response",
    "safe_json_serialize",
    "generate_claim_number",
    "generate_workflow_id",
    "generate_batch_id",
    "validate_claim_amount",
    "format_currency",
    "is_round_number",
    "ensure_timezone_aware",
    "days_between",
    "is_future_date",
    "chunk_list",
    "deduplicate_by_key",
    "safe_get_nested",
    "truncate_string",
    "sanitize_for_logging",
    "RetryConfig",
    "validate_uuid",
    "validate_email",
    "validate_policy_number",
    # Error Handling
    "ErrorResponse",
    "exception_to_response",
    "get_http_status",
    "handle_exception",
    "create_error_handlers",
    "error_boundary",
    "raise_not_found",
    "raise_validation_error",
    "raise_circuit_open",
    "raise_rate_limit",
    "Result",
]
